services:
  backend:
    container_name: ${APP_NAME}_backend
    build:
      context: backend
      dockerfile: Dockerfile.development
    env_file:
      - .env
    stdin_open: true
    ports:
      - ${BACKEND_PORT}:3100
      - ${PRISMA_STUDIO_PORT}:5555
    volumes:
      - ./backend:/backend

  frontend:
    container_name: ${APP_NAME}_frontend
    build:
      context: frontend
      dockerfile: Dockerfile.development
    env_file:
      - .env
    stdin_open: true
    ports:
      - ${FRONTEND_PORT}:3000
      - ${FRONTEND_PORT_HRM}:3010
    volumes:
      - ./frontend:/frontend

  postgres:
    container_name: ${APP_NAME}_postgres
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  mails:
    container_name: ${APP_NAME}_mails
    build:
      context: mails
      dockerfile: Dockerfile
    ports:
      - ${MAILS_PORT}:3000
    volumes:
      - ./mails:/mails

  mailpit:
    container_name: ${APP_NAME}_mailpit
    image: axllent/mailpit
    ports:
      - ${MAILPIT_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025

volumes:
  postgres:
