FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run db:generate
RUN npm run build

RUN chmod +x entrypoint.sh

EXPOSE 3100
ENTRYPOINT ["./entrypoint.sh"]
CMD ["npm", "run", "start:prod"]
