/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface RefreshTokenStates {
  createdAt: Generated<Timestamp>;
  id: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string;
  userId: string;
}

export interface Users {
  blocked: boolean;
  createdAt: Generated<Timestamp>;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  password: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  refreshTokenStates: RefreshTokenStates;
  users: Users;
}
